from .attacker import Attacker
from .detective import Detective
from .doctor import Doctor
from .godfather import Godfather
from .hitman import Hitman
from .independent import Independent
from .investigator import Investigator
from .joker import Joker
from .mafia import Mafia
from .mayor import Mayor
from .player import Player
from .protector import Protector
from .sniper import Sniper
from .villager import Villager
