from .attacker import AttackerPlayer
from .detective import DetectivePlayer
from .doctor import DoctorPlayer
from .godfather import Godfather
from .hitman import HitmanPlayer
from .independent import IndependentPlayer
from .investigator import InvestigatorPlayer
from .joker import JokerPlayer
from .mafia import MafiaPlayer
from .mayor import Mayor
from .player import Player
from .protector import ProtectorPlayer
from .sniper import SniperPlayer
from .villager import VillagerPlayer
